### ISSUE TITLE
allocine.class.php

### ISSUE THREAD

**Issue by rokado** [dlenettr/film-reader-plugins#1]
Hi .

Thank you for plugin update but he doesnt work correctly.

Film Genres (genres) and Film Release Date (date de sortie)  no info found.

Film Stars :  the director is always copied first in this fields with all the stars just after.
ex: 
Film Director:  Steven Spielberg
Film Stars: Steven Spielberg, Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough

Film Story (Synopsis et détails) only 50% are copied because you use meta[@property="og:description"] who is truncate on allocine.

Hope i am clear in my descriptions.
Thank you.

Regards Rokado

**Comment by dlenettr** [comment]
Hi, I'll check it soon.
